version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git config --global user.name "ItsVixano"
           git config --global user.email "vixanonew@gmail.com"
           git config --global color.ui false
           wget https://raw.githubusercontent.com/flashokillerify/twrp_d2s/master/.circleci/script.sh
           source script.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
